# Generated by Django 4.2.1 on 2023-06-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
    ]
