# Generated by Django 4.2.1 on 2023-06-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_poduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
